api/urls.py
from django.conf.urls import url
from api.views import *

urlpatterns = [
    url(r'^all/$', PostListAPIView.as_view(), name="all"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    url(r'^update/(?P<post_slug>[-\w]+)/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^comment/list/$', CommentListAPIView.as_view(), name="comment_list"),
    url(r'^comment/create/$', CommentCreateAPIView.as_view(), name="comment_create"),
    url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
    url(r'^login/$', UserLoginAPIView.as_view(), name="login"),
]

drill/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homebrew import views
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^', include('homebrew.urls', namespace="homebrew")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^api/', include('api.urls', namespace="api")),
    
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homebrew/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^home/', views.home, name="home"),
    url(r'^fourth/', views.fourth, name="fourth"),
    url(r'^day/', views.day, name="day"),
    url(r'^task/', views.task, name="task"),
    url(r'^all/$', views.allobj, name="allobj"),
    url(r'^intlink/(?P<post_slug>[-\w]+)/$', views.intlink, name="intlink"),
    url(r'^create/', views.create, name="create"),
    url(r'^update/(?P<post_slug>[-\w]+)/$', views.update, name="update"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', views.delete, name="delete"),
    url(r'^ajax_like/(?P<post_number>\d+)/$', views.ajax_like, name="like_button"),
    url(r'^signup/$', views.usersignup, name="signup"),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^logout/$', views.userlogout, name="logout"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homebrew/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User

class Brew(models.Model):
	title = models.CharField(max_length=50)
	author = models.ForeignKey(User, default=1)
	slug = models.SlugField(unique=True)
	number = models.IntegerField()
	date = models.DateField()
	email = models.EmailField()
	image = models.ImageField(null=True, blank=True, upload_to="post_images")
	publish = models.DateField(auto_now=False, auto_now_add=False)
	draft = models.BooleanField(default=False)


	def __str__(self):
		return self.title

	def absurl(self):
		return reverse("homebrew:intlink", kwargs={"post_slug": self.slug})

def create_slug(instance, new_slug=None):
	slug = slugify (instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Brew.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s"%(slug,qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_reciever,sender=Brew)

class Like(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Brew)
	created = models.DateTimeField(auto_now_add=True)
	
# Create your models here.

homebrew/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import Brew, Like
from django.shortcuts import get_object_or_404
from .create import PostForm, UserSignup, UserLogin
from django.contrib import messages 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout 

def userlogout(request):
    logout(request)
    return redirect("homebrew:all")

def userlogin(request):
    context = {}
    form = UserLogin()
    context['form'] = form
    if request.method == 'POST':
        form = UserLogin(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                return redirect('homebrew:list')

            messages.error(request, "Wrong username/password combination. Please try again.")
            return redirect("homebrew:login")
        messages.error(request, form.errors)
        return redirect("homebrew:login")
    return render(request, 'login.html', context)

def usersignup(request):
    context = {}
    form = UserSignup()
    context['form'] = form
    if request.method == 'POST':
        form = UserSignup(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = user.password

            user.set_password(password)
            user.save()

            auth_user = authenticate(username=username, password=password)
            login(request, auth_user)

            return redirect("homebrew:all")
        messages.error(request, form.errors)
        return redirect("homebrew:signup")
    return render(request, 'signup.html', context)


def home(request):
	return HttpResponse("<h1>Hello World</h1>")
def fourth(request):
	return render(request, 'fourth.html', {})
def day(request):
	return HttpResponse("<h1>Day</h1>")
def task(request):
	return HttpResponse("<h1>Task</h1>") 

def allobj(request): #post_list
	today = timezone.now().date()
	# post_list = Brew.objects.all() #.order_by("-date","-title") #ordering by list & title
	post_list = Brew.objects.filter(draft=False).filter(publish__lte=today)

	query = request.GET.get("q")
	if query:
		post_list = post_list.filter(
			Q(title__icontains=query)|
			Q(number__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()

	paginator = Paginator(post_list, 4)
	page = request.GET.get("page")
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	context = {
	"post_list": posts,
	"user": request.user,
	"today": today,
	}
	return render(request, 'allobj.html', context) 

def intlink(request, post_slug): #post_detail
	obj = get_object_or_404(Brew, slug = post_slug)
	if obj.publish > timezone.now().date() or obj.draft:
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
			
	if request.user.is_authenticated():
		if Like.objects.filter(post=obj, user=request.user).exists():
			liked = True
		else:
			liked = False
	post_like_count = obj.like_set.all().count()

	context = {
	"input": obj,
	"share_string": quote(obj.title),
	"post_like_count":post_like_count,
	"liked":liked
	}
	return render(request, 'oneobj.html', context) 

def create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		post = form.save(commit=False)
		post.author = request.user
		post.save()
		messages.success(request, "Welcome to the world, Instance.")
		return redirect("homebrew:allobj")
	context = {
	"title": "Create",
	"form": form,
	}
	return render(request, 'create.html', context)

def update(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Brew, slug =post_slug)
	form = PostForm(request.POST or None, request.FILES or None, instance = instance)
	if form.is_valid():
		form.save()
		messages.success(request, "Ta3deel!")
		return redirect(instance.absurl())
	context = {
	"form": form,
	"instance": instance,
	"title": "Update",
	}
	return render(request, 'update.html', context)

def delete(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Post, slug = post_slug)
	instance.delete()
	messages.success(request, "Bye!")
	return redirect("homebrew:allobj")

def ajax_like(request, post_id):
    post_object = Post.objects.get(id=post_id)
    new_like, created = Like.objects.get_or_create(user=request.user, post=post_object)

    if created:
        action="like"
    else:
        new_like.delete()
        action="unlike"

    post_like_count = post_object.like_set.all().count()
    response = {
        "action": action,
        "post_like_count": post_like_count,
    }
    return JsonResponse(response, safe=False)

homebrew/templates/allobj.html
{% extends "base.html" %}

{% block title %}
Entries List
{% endblock title %}

{% block content %}


<h2> Posts List </h2><br>


{% for instance in post_list %}
  <a href="{{instance.absurl}}" class="list-group-item">
    <h4 class="list-group-item-heading">{{instance.title}}</h4>
      <div class="thumbnail">
    {% if instance.image %}
        <img src="{{instance.image.url}}" alt="" class="img-responsive">
    {% endif %}
    </div>
    <div class="caption">
    </div>
    <p class="list-group-item-text">
    <strong>{{instance.number}}</strong><br>{{instance.email}}<br><small>{{instance.date}}</small>
           <a href="{{instance.absurl}}" class="btn btn-primary" role="button">View</a>
    <a href="{% url 'homebrew:update' post_slug=instance.slug %}" class="btn btn-info" role="button">Update</a>
    </p>
  </a>
<br>
{% endfor %}
</div>


<div class="pagination">
        <span class="step-links">
            {% if post_list.has_previous %}
                <a href="?page={{ post_list.previous_page_number }}&q={{ request.GET.q }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
            </span>

            {% if post_list.has_next %}
                <a href="?page={{ post_list.next_page_number }}&q={{ request.GET.q }}">next</a>
            {% endif %}
        </span>
    </div>

{% endblock content %}

homebrew/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}

    {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
    {% block style %}

    {% endblock style %}
    </style>
</head>
<body>
{% include "navbar.html" %}
{% include "messages.html" %}
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

homebrew/templates/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
CREATION
{% endblock title %}

{% block content %}

<form action="{% url 'homebrew:create' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
    <h1>The Post {{title}} Page</h1>
    {{form.as_p}}
    <input type="submit" value="Create Post">
 </form>

{% endblock content %}

homebrew/templates/django_comments.html
{% load comments %}
{% get_comment_list for input as comments %}

{% for comment in comments %}
    <div class="alert alert-info" role="alert"><b>{{ comment.user_name }} said:</b> {{ comment.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for input as form %}
<form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
	<input type="hidden" name="name" value="{{ request.user.username }}">
    <input type="hidden" name="email" value="{{ request.user.email }}">
    <input type="text" class="form-control input-lg" name="comment">
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="next" value="{{input.absurl}}">
    <input type="submit" name="submit" class="btn btn-primary">
</form>

homebrew/templates/fourth.html
<!DOCTYPE html>
<html>
<head>
	<title>fourth render</title>
	<style>
	@import url('https://fonts.googleapis.com/css?family=Roboto');
	body {
		background-color: crimson;
	}
	h1 {
		font-size: 80px;
		font-family: verdana;
	}
	#img {
		align: center;
		border: dashed;
	}
	ol {
		font-family: Roboto;
		font-size: 40px;
	}
	</style>
</head>
<body>
<h1>DONE!</h1>
<ol>
<li>one</li>
<li>two</li>
<li>three</li>
<li>roboto font</li>
</ol>
<img src="https://i.vimeocdn.com/portrait/58832_300x300" id="img">
</body>
</html>

homebrew/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Login
{% endblock title %}


{% block content %}
    <form action="{% url 'homebrew:login' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Login">
    </form>
{% endblock content %}

homebrew/templates/messages.html
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

homebrew/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'homebrew:allobj' %}">YG Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="http://localhost:8000/admin/">Admin Page</a></li>
        <li><a href="{% url 'homebrew:create' %}">Create Post</a></li>

      </ul>
      <form class="navbar-form navbar-left" method="GET">
        <div class="form-group">
    <input type="text" name='q' placeholder="Search posts" value="{{request.GET.q}}">
    <input type="submit" class="btn btn-default" value="Search">
        </div>
      </form>
    </div>
  </div>
</nav>
<br><br><br>

homebrew/templates/oneobj.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block title %}
One Entry Details
{% endblock title %}

{% block content %}
<br><br>
<h1>ID Page</h1>
<h2></h2>
<ul id="new">
{% if input.image %}Image: <img src="{{input.image.url}}" class="img-responsive">{% endif %}
Title: {{input.title}}<br>
Author: {{input.author.get_full_name}}<br><br>
Number: {{input.number}}<br>
Date: {{input.date}}<br>
Email: {{input.email}}<br>

</ul>

{% include 'django_comments.html' %}
<button class="btn">
    <span id="likes_count">{{ post_like_count }}</span>
    <span id= "heart" class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}" aria-hidden="true"></span>
</button>

<br><br>
<a href="https://www.facebook.com/sharer/sharer.php?u={{request.absurl}}">
Share on Facebook
</a><br>
<a href="https://twitter.com/home?status={{input.title|truncatechars:35|urlify}}%20{{request.absurl}}">
    Share on Twitter
</a><br>
<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.absurl}}&title={{input.title|urlify}}&summary={{input.number|truncatechars:35|urlify}}&source={{request.absurl}}">
Share on Linkedin
</a><br>

<br><br>
<a href="{% url 'homebrew:allobj' %}">Go back to list</a>
<br><br>

<script type="text/javascript">
    function ajax_like() {
        console.log("Like/Unlike clicked!");
        $.ajax(
            {
                type:'GET',
                url: '{% url "homebrew:like_button" post_id=input.id %}',
                error: function(){
                    console.log('error');
                },
                success: function(data){ 
                    $("#likes_count").text(data.post_like_count);

                    if(data.action==="like"){
                        $("#heart").addClass("text-danger");
                    }else{
                        $("#heart").removeClass("text-danger")  
                    }
                },
            }
        );
    }
</script>

{% endblock content %}

homebrew/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Sign Up
{% endblock title %}


{% block content %}
    <form action="{% url 'homebrew:signup' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Sign Up">
    </form>
{% endblock content %}

homebrew/templates/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
UPDATE
{% endblock title %}

{% block content %}  

    <h1>The Post {{title}} Page</h1>
    <form action="{% url 'homebrew:update' post_slug=instance.slug %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update Post">
    </form>

{% endblock content %}